### ISSUE TITLE
Document new attributes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#100]
https://github.com/metanorma/metanorma-ribose/blob/8fb6910360cb8ad16eeefb5be85ff736fd021ba8/lib/asciidoctor/ribose/boilerplate.xml#L33-L43

* :publisher:
* :pub-address:
* :pub-email:
* :pub-uri:
* Author information

**Comment by opoudjis** [comment]
https://www.metanorma.org/author/ref/document-attributes/

This is an include issue. I am not going to repeat the same document attribute values in the documentation of 15 flavours.

**Comment by ronaldtse** [comment]
`pub-address` is not documented anywhere.

**Comment by ronaldtse** [comment]
Oh it is! Goodness. Can't believe you're right.
