### ISSUE TITLE
(URGENT) Ribose PDF: "Report" type should not show as "{publisher} report" but just "Ribose report"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#102]
<img width="774" alt="Screenshot 2021-05-31 at 8 36 32 PM" src="https://user-images.githubusercontent.com/11865/120194228-eda2b380-c24f-11eb-8167-7b363fae0873.png">

**Comment by Intelligent2013** [comment]
Ribose xslt updated.
