### ISSUE TITLE
(URGENT) Ribose PDF: "All right reserved" should be preceded with a period

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#103]
<img width="574" alt="Screenshot 2021-05-31 at 8 37 43 PM" src="https://user-images.githubusercontent.com/11865/120194360-175bda80-c250-11eb-9aeb-d7be0327bad6.png">

"{year} {publisher}. All rights reserved"

**Comment by Intelligent2013** [comment]
@ronaldtse Ribose xslt updated.
