### ISSUE TITLE
(URGENT) Ribose PDF: References with dates are not formatted correctly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#105]
<img width="568" alt="Screenshot 2021-05-31 at 8 43 42 PM" src="https://user-images.githubusercontent.com/11865/120195063-ed56e800-c250-11eb-842a-fd46ba6d0527.png">

```adoc
* [[[RFC7991,IETF RFC 7991]]], _AUTOFILL_

* [[[ISO690,ISO 690]]], _AUTOFILL_
```

**Comment by ronaldtse** [comment]
This is the ISO 690 format:

INTERNET ENGINEERING TASK FORCE (IETF). RFC 7991, The “xml2rfc” Version 3 Vocabulary. Online. P. HOFFMAN (ed.). 2016. Available from: https://www.ietf.org/rfc/rfc7991.txt. [viewed 2021-02-10].

If this is too complex to generate immediately, just add a space between the document and the date.

**Comment by Intelligent2013** [comment]
@ronaldtse looks like in xslt I didn't not realized all displaying rules for bibliography items. But this issue similar to: https://github.com/metanorma/mn-native-pdf/issues/285 and https://github.com/metanorma/metanorma-nist/issues/210
where we decided to move logic into presentation xml.
Space before date added into xslt.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 , I kind of guessed it is about presentation XML so it is pending implementation indeed...
