### ISSUE TITLE
(URGENT) Ribose PDF: Use Source Sans Pro "semibold" for clause headings

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#106]
Too bold right now.

<img width="584" alt="Screenshot 2021-05-31 at 9 15 34 PM" src="https://user-images.githubusercontent.com/11865/120199040-60faf400-c255-11eb-807e-b3ac4386e443.png">

**Comment by Intelligent2013** [comment]
Done.
