### ISSUE TITLE
(URGENT) Ribose PDF: alternate term should stay closer to the term heading, and have margin to definition

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#107]
<img width="559" alt="Screenshot 2021-05-31 at 9 17 19 PM" src="https://user-images.githubusercontent.com/11865/120199265-9f90ae80-c255-11eb-8045-4af0f06f8b75.png">

**Comment by Intelligent2013** [comment]
@ronaldtse it's ok?
![image](https://user-images.githubusercontent.com/5559926/120211392-9265c680-c239-11eb-94c9-0b63fa14af85.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 yes! Can you also apply bolding to the SaaS term so the reader can see them as equivalent? Thanks.

**Comment by Intelligent2013** [comment]
Done.
![image](https://user-images.githubusercontent.com/5559926/120216422-aad8df80-c23f-11eb-93ff-a94df6078c9c.png)
