### ISSUE TITLE
(URGENT) Ribose PDF: even pages should have hexagons on top right, odd pages have hexagons bottom left

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#108]
<img width="627" alt="Screenshot 2021-05-31 at 9 28 27 PM" src="https://user-images.githubusercontent.com/11865/120200695-2e51fb00-c257-11eb-8e67-119622a6f784.png">

<img width="629" alt="Screenshot 2021-05-31 at 9 28 37 PM" src="https://user-images.githubusercontent.com/11865/120200716-3447dc00-c257-11eb-888c-be59e1005d0a.png">

**Comment by Intelligent2013** [comment]
@ronaldtse sometimes text displays on top right hexagons. It's ok?

![image](https://user-images.githubusercontent.com/5559926/120213493-ef627c00-c23b-11eb-8656-d421ffd705c0.png)

-------------

![image](https://user-images.githubusercontent.com/5559926/120213562-06a16980-c23c-11eb-86a0-deb8ba88b379.png)


We can increase a top margin to 2-3cm, but useful text area on page will be decreased.

**Comment by ronaldtse** [comment]
@Intelligent2013 yes, some overlap is okay. Thanks!

**Comment by Intelligent2013** [comment]
Done.
