### ISSUE TITLE
(URGENT) Ribose PDF: Introduction section should adhere to first level clause heading style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#111]
Design:

<img width="847" alt="Screenshot 2021-05-31 at 9 38 18 PM" src="https://user-images.githubusercontent.com/11865/120201931-8dfcd600-c258-11eb-93e0-59190e4d4131.png">

Actual:
<img width="898" alt="Screenshot 2021-05-31 at 9 38 32 PM" src="https://user-images.githubusercontent.com/11865/120201956-97863e00-c258-11eb-8c18-de8e411ce4ce.png">

**Comment by Intelligent2013** [comment]
Done.
