### ISSUE TITLE
Ribose PDF: Use Ribose SVG logo for vector logo

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#112]
[ribose logo normal.svg.zip](https://github.com/metanorma/metanorma-ribose/files/6570632/ribose.logo.normal.svg.zip)

**Comment by Intelligent2013** [comment]
Svg logo added. Done.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ronaldtse** [comment]
Confirmed!
