### ISSUE TITLE
Move citation processing to presentation XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#114]
This was originally posted in #105 but the real reason is that PDF processing can't deal with reproducing citation rendering logic of so many flavors.

In Ribose flavor we want ISO 690 citations.

Source:
```adoc
* [[[RFC7991,IETF RFC 7991]]], _AUTOFILL_

* [[[ISO690,ISO 690]]], _AUTOFILL_
```

<img width="568" alt="Screenshot 2021-05-31 at 8 43 42 PM" src="https://user-images.githubusercontent.com/11865/120195063-ed56e800-c250-11eb-842a-fd46ba6d0527.png">

**Comment by opoudjis** [comment]
This is going back to High from Urgent. I'm doing all the citation refactoring together, and I'm not the one interrupting implementation of that with ZOMG ISO GAVE US URGENT FEEDBACK ON RENDERING.

**Comment by opoudjis** [comment]
Covered in https://github.com/metanorma/metanorma-standoc/issues/479
