### ISSUE TITLE
Update PDF styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#116]
[Ribose Document Design_v5.pdf](https://github.com/metanorma/metanorma-ribose/files/6613324/Ribose.Document.Design_v5.pdf)

This updates designs for:
1. tables, their margins and captions
2. figures
3. “NOTEs”, “EXAMPLEs” and “source”
4. Lists: definition lists, numbered lists, bullet lists
5. Definitions section
6. “Yellow honeycombs” now have different opacity settings, and the text area for odd/even pages has changed.
7. Hyperlink style

**Comment by Intelligent2013** [comment]
>     6. “Yellow honeycombs” now have different opacity settings, and the text area for odd/even pages has changed.

@ronaldtse could you attach "honeycombs" as separated images (or attach source Indesign file)? Very hard to extract them from PDF and clean from text.
1. What does mean "different opacity settings"? I see that they have different colors. Or something else?
2. The pages started from 6 don't have "honeycombs". Should I make it in PDF also? Or all pages should have "honeycombs"?

**Comment by Intelligent2013** [comment]
@ronaldtse 3. what is the source xml tag for 'Entry status'?
![image](https://user-images.githubusercontent.com/5559926/121237582-dee77c80-c89f-11eb-82f1-24730de42748.png)

**Comment by ronaldtse** [comment]
> what is the source xml tag for 'Entry status'?

I think this can be ignored.

**Comment by ronaldtse** [comment]
> 1. What does mean "different opacity settings"? I see that they have different colors. Or something else?
> 2. The pages started from 6 don't have "honeycombs". Should I make it in PDF also? Or all pages should have "honeycombs"?

I have asked designer for the source. Will update.

**Comment by ronaldtse** [comment]
From designer:

> I think we can alternate between yellow, blue and orange honeycombs for each page

[Ribose Document Design_v5.pdf](https://github.com/metanorma/metanorma-ribose/files/6635305/Ribose.Document.Design_v5.pdf)

For the honeycombs, let's do this.

* There are two variables: placement and color. 
  * placement 2 configurations
    * Every 2 pages (even/odd: 2, 3; 4, 5; ...) is a pair
    * We want "opposing honeycombs" at every pair page. i.e. left bottom + right top, left top + right bottom.
  * color: 3 configurations
    * yellow, blue and orange
* These variables will increment per page pairs.

i.e.
* Page 2 and 3: (left bottom + right top, yellow)
* Page 4 and 5: (left top + right bottom, blue)
* Page 6 and 7: (left bottom + right top, orange)
* Page 8 and 9: (left top + right bottom, yellow)
* ...

Like this:
<img width="1077" alt="Screenshot 2021-06-11 at 10 11 45 AM" src="https://user-images.githubusercontent.com/11865/121621085-0a37ba80-ca9e-11eb-833e-4b9bf5d09365.png">

<img width="1084" alt="Screenshot 2021-06-11 at 10 11 25 AM" src="https://user-images.githubusercontent.com/11865/121621076-060b9d00-ca9e-11eb-85dd-841a49c0d675.png">

**Comment by Intelligent2013** [comment]
At first glance it looks not possible. Xsl-fo has 'even' and 'odd' conditional page sequence only. I'll try to investigate how to do it via apache fop intermediate format...

**Comment by Intelligent2013** [comment]
Done. Apache IF is too complicated for using. Page sequences will be created on-fly via XSLT. XSLT inserts 24 page sequence 50 times (1200 pages I hope will be enough, but for >1200 page will be used layout as for first page).

**Comment by ronaldtse** [comment]
Updated fonts to Open Sans.

[Ribose Document Design_v6.pdf](https://github.com/metanorma/metanorma-ribose/files/6713304/Ribose.Document.Design_v6.pdf)

**Comment by Intelligent2013** [comment]
> 
> 
> Updated fonts to Open Sans.
> 

Ribose xslt updated.
