### ISSUE TITLE
PDF: Styling inconsistencies: NOTE in text vs NOTE in table styled differently

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#119]
NOTE in text vs NOTE in table styled differently.
<img width="812" alt="Screenshot 2021-10-03 at 12 04 13 PM" src="https://user-images.githubusercontent.com/11865/135739203-81636c08-a3e8-445b-bbe7-31e6ffdf3ecb.png">
<img width="730" alt="Screenshot 2021-10-03 at 12 04 21 PM" src="https://user-images.githubusercontent.com/11865/135739207-2b99a633-15b4-4163-9e21-63dcd833cdcb.png">

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/135749940-1a9f9aa8-4d75-41ef-8e9c-25164cbc059f.png)
