### ISSUE TITLE
PDF: Figure blocks inconsistent in styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#120]
Figures usually have a background

<img width="781" alt="Screenshot 2021-10-03 at 12 06 58 PM" src="https://user-images.githubusercontent.com/11865/135739280-5e073325-3ff9-4b74-b2e6-5652bf40dcbf.png">

Block of source code need to be delimited with background to ensure visible difference as normal figure. Notice that the "Figure 1" and "Figure B.1" title style is very different, they should be identical.

<img width="765" alt="Screenshot 2021-10-03 at 12 06 12 PM" src="https://user-images.githubusercontent.com/11865/135739254-a61a33b8-0129-4931-9fba-f9141e4c31c0.png">

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/135750098-f3b749cb-dc32-477c-9879-226313e41e68.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Can we also unbold the hyperlinks?

**Comment by Intelligent2013** [comment]
> Can we also unbold the hyperlinks?

Done:
![image](https://user-images.githubusercontent.com/5559926/135838331-fea9d1a6-b9ca-4a4a-8bcb-51da550e531f.png)

**Comment by ronaldtse** [comment]
Thanks!

Notice that in this screenshot the "reportnumber" font size and the normal font size is very different. Can we fix this?

**Comment by Intelligent2013** [comment]
Inconsistency fixed. Also, the font-size for `sourcecode` increased up to value as main text (there was 90%):
![image](https://user-images.githubusercontent.com/5559926/135854762-d06df6fb-9686-4b41-899b-e9bf48473d23.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
