### ISSUE TITLE
PDF: enlarge the text font sizes (normal, monospace, etc)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#123]
In the PDF, can we enlarge the text font sizes (normal, monospace, etc)? They are too small compared with normal content text.

<img width="541" alt="Screenshot 2021-12-22 at 4 30 48 PM" src="https://user-images.githubusercontent.com/11865/147061210-9eb8a040-9789-4f34-8d3c-88595211928a.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ribose/issues/122#issuecomment-999385345_

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/147078459-09d4ac3f-0dcb-4732-a258-f3a78da6e452.png)

**Comment by Intelligent2013** [comment]
Closing.
