### ISSUE TITLE
PDF: List item styling and indents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#124]
Let's remove the numbered list number indent:
<img width="448" alt="Screenshot 2021-12-22 at 4 33 31 PM" src="https://user-images.githubusercontent.com/11865/147061679-da79bdba-baad-471a-a8d9-da3904b0bb04.png">

Because unnumbered list items have no item indent:
<img width="519" alt="Screenshot 2021-12-22 at 4 34 02 PM" src="https://user-images.githubusercontent.com/11865/147061711-c36e3355-1a1d-4984-9636-23405009e187.png">

There seems to be a difference in list item indent in some places, but the encoding is identical (with the list items that do not have item indent). This is an inconsistency we need to fix:

<img width="344" alt="Screenshot 2021-12-22 at 4 34 51 PM" src="https://user-images.githubusercontent.com/11865/147061842-f7a8800a-2e80-4c25-ae8d-2448e57e54e9.png">

Let's also tweak the sub-level indents and styling. They don't look so nice (maybe use emdash instead of hyphen, and also every level indent should have a different bullet style):
<img width="528" alt="Screenshot 2021-12-22 at 4 35 56 PM" src="https://user-images.githubusercontent.com/11865/147061998-5345eecf-cb0e-451f-8893-f606f2fa72e9.png">

We should reduce the indent in the orange areas:
<img width="528" alt="Screenshot 2021-12-22 at 4 39 12 PM" src="https://user-images.githubusercontent.com/11865/147062637-0405016e-18dc-40e2-a2a3-b62a990306ac.png">

**Comment by Intelligent2013** [comment]
Done ([document.presentation.pdf](https://github.com/metanorma/metanorma-ribose/files/7762018/document.presentation.pdf)):



![image](https://user-images.githubusercontent.com/5559926/147078607-99267c1e-c6a0-45e2-a601-db11a8089b37.png)

--------------------

![image](https://user-images.githubusercontent.com/5559926/147078696-4bf606c8-e8ad-4a36-ae05-81934f8eef7e.png)

-------------------

![image](https://user-images.githubusercontent.com/5559926/147078845-8c16d662-3877-4459-841e-27cd629ac346.png)

**Comment by ronaldtse** [comment]
Thank you! Can we make the orange lengths a bit shorter?
<img width="551" alt="Screenshot 2021-12-22 at 7 01 15 PM" src="https://user-images.githubusercontent.com/11865/147082783-e49e45b9-83fe-4187-9775-9cdc68987984.png">

**Comment by Intelligent2013** [comment]
> Can we make the orange lengths a bit shorter?

@ronaldtse done ([document.presentation.pdf](https://github.com/metanorma/metanorma-ribose/files/7762782/document.presentation.pdf)):
![image](https://user-images.githubusercontent.com/5559926/147097439-8208eb3b-a345-463d-91b4-5594f902071c.png)

Also it affects on ordered lists:
![image](https://user-images.githubusercontent.com/5559926/147097554-c627b64e-f3a5-4f59-b1c1-5761abe7d460.png)

Please inform me if I need to do different indents for ul and ol lists.

**Comment by ronaldtse** [comment]
@Intelligent2013 this looks good. How many bullet styles for unnumbered list items do we have right now?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 this looks good. How many bullet styles for unnumbered list items do we have right now?

@ronaldtse in Ribose xslt we have three styles:
- bullet
- em dash
- circle (actually letter 'o')

(4th level will be marked with bullet, 5th with em dash, etc.)

But this list can be expanded.

For another xslts, only bullet or dash only, so I'll update them also.

**Comment by ronaldtse** [comment]
Can we use the "dot with circle" as first level, then the dash (let's change it to the ISO style long dash), then the "dot" (the dot looks a bit small)?

**Comment by Intelligent2013** [comment]
>  Can we use the "dot with circle" as first level, then the dash (let's change it to the ISO style long dash), then the "dot" (the dot looks a bit small)?

Done ([document.presentation.pdf](https://github.com/metanorma/metanorma-ribose/files/7768531/document.presentation.pdf)):

![image](https://user-images.githubusercontent.com/5559926/147225816-df9b070b-b25e-4515-a1a4-958222126893.png)

**Comment by Intelligent2013** [comment]
Closing.
