### ISSUE TITLE
PDF: Support Letter format output

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#130]
Letter layout is necessary for some US documents:

> (6) Page size. 21.6 centimeters by 27.9 centimeters (8 1/2 inches by 11 inches).

**Comment by ronaldtse** [comment]
Probably!

**Comment by Intelligent2013** [comment]
All Ribose PDF have letter paper size already:
![image](https://user-images.githubusercontent.com/5559926/171109006-1eb6a673-59b8-4e5e-bd7c-52fd5381297b.png)

Do you need support 'redefine' for another SDO?

**Comment by Intelligent2013** [comment]
In any case, I've added processing for the attribute `:presentation-metadata-papersize:`. Now xslt can change paper sizes: 'letter' and 'a4' (in any upper- lower- case, ie. 'Letter', 'A4').

Just for memory, default paper size 'Letter' is using for CSA, M3AAWG, NIST, OGC and Ribose PDFs.
'A4' - for another.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
