### ISSUE TITLE
Example of rsd format missing from repo

### ISSUE THREAD

**Issue by danyill** [metanorma/metanorma-ribose#69]
References to this repository from https://www.metanorma.com/author/rsd/sample/ suggest there is sample document:

```
git clone https://github.com/metanorma/metanorma-rsd.git

cd /spec/examples/
```

There is no `spec/examples` in this repository... (The leading slash also doesn't look quite right in the command)

This may not be the correct place to file this issue but it's where edits are suggested and I cannot see an example anywhere in this repo. Just noticed in passing.

**Comment by ronaldtse** [comment]
@danyill thanks for raising the issue! I believe we are going to create samples at https://github.com/metanorma/mn-samples-ribose (which is empty now).

Ping @opoudjis (for the missing document in `spec/examples`) and @metanorma/editors (for the website)

(Actually, metanorma-ribose is a private document flavor and is only meant for internal usage. Did you have another need that brought you here?)

**Comment by danyill** [comment]
Thanks @ronaldtse I was just looking for a simplish example of a standardisation format and on the spur of the moment thought rsd might be a good place to start.

I am interested in standardisation and Asciidoctor and I am interested in the grammars developed here, the different output formats and the tooling. I think you're all doing great work and I like to explore it from time to time. Keep it up :+1:

**Comment by opoudjis** [comment]
We did get rid of spec/examples systematically, and replaced them with samples repositories, e.g. https://github.com/metanorma/mn-samples-ribose for the Ribose flavour (which is empty, and @ronaldtse, you'll need to work out what document you'd like to see there). I'll update the readme to remove the spec/examples reference.

**Comment by ronaldtse** [comment]
Tasks:
* https://github.com/metanorma/mn-samples-ribose/issues/1
* https://github.com/metanorma/mn-samples-ribose/issues/2

**Comment by ronaldtse** [comment]
Already available at https://github.com/metanorma/mn-samples-ribose . Closing.
