### ISSUE TITLE
Allow configuring the entity name and address

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#91]
There are multiple entities that share this flavor.

We need document attributes to configure:
- entity name (e.g. Ribose Limited) (shown on cover page, page header and page footer)
- entity address (e.g. 3rd Floor, 11-12 St James’s Square, London, SW1Y 4LB, United Kingdom) (shown in copyright message)
- copyright email address  (shown in copyright message)
- website (shown in copyright message)

**Comment by opoudjis** [comment]
These are already implemented as the attributes:

* `:publisher:`
* `:pub-address:`
* `:pub-email:`
* `:pub-uri:`

But I need to confirm that those overrides work in the flavour for the cover.

**Comment by opoudjis** [comment]
Successful. The boilerplate will default to 

````
<p align="left" id="boilerplate-name">
        Ribose Group Inc.
      </p>
      <p align="left" id="boilerplate-address">Suite 1, 8/F, New Henry House<br/>
        10 Ice House Street<br/>
        Central<br/>
        Hong Kong<br/>
        <br />
        <link target="mailto:copyright@ribose.com">copyright@ribose.com</link><br />
        <link target="https://www.ribose.com">www.ribose.com</link>
      </p>
````

but will plug in values supplied above if given.
