### ISSUE TITLE
Copyright message flipped in order

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#92]
Originally:
<img width="642" alt="Screenshot 2021-03-30 at 1 22 53 PM" src="https://user-images.githubusercontent.com/11865/112937863-09f47800-915b-11eb-9e54-803c9e19e729.png">

Should be:
<img width="636" alt="Screenshot 2021-03-30 at 1 23 10 PM" src="https://user-images.githubusercontent.com/11865/112937881-15e03a00-915b-11eb-8d1c-ea6e6eed7290.png">

**Comment by opoudjis** [comment]
Have just implemented in Word and HTML; this is flipping of rendering of feedback-boilerplate and license-boilerplate elements.

**Comment by Intelligent2013** [comment]
Ribose XSLT updates for showing `feedback-statement` element.
