### ISSUE TITLE
(URGENT) Cross-document href links inadvertently replace `/` with `_`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#96]
Rendered HTML:
```html
<p id="_9510918a-c90d-48c7-8c3d-69d76e162c20">analyses and evaluates risks to the firm’s
<a href=".._crimson-context_document.html#chap-appendices-performance-aspects">Performance Aspects</a></p>
...
```

Original:
```adoc
* analyses and evaluates risks to the firm's
<<../crimson-context/document.adoc#chap-appendices-performance-aspects, Performance Aspects>>
```

This used to work but I suspect these links have been sanitised in the XML and no longer link properly.

**Comment by ronaldtse** [comment]
Links to PDF would also work: https://helpx.adobe.com/acrobat/kb/link-html-pdf-page-acrobat.html

**Comment by opoudjis** [comment]
We introduce a convention whereby links to .adoc documents will be substituted on rendering with .pdf, .html, .doc depending on the type of document being rendered. We will make this an added link parameter, `%updatetype`.

So `http://../crimson-context/document.adoc#chap-appendices-performance-aspects.adoc[Performance Aspects,%updatetype]`

**Comment by ronaldtse** [comment]
Do you mean `link:../crimson-context/document.adoc#chap-appendices-performance-aspects.adoc[Performance Aspects,%updatetype]`?

**Comment by opoudjis** [comment]
Both will work, I believe. Am about to find out.
