### ISSUE TITLE
Metanorma PDF links

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-ribose#98]
Follow on from https://github.com/metanorma/metanorma-ribose/issues/96

If you receive `//link[@updatetype = "true"]`, then insert a `.pdf` suffix after the `//link/@target` (so long as the target is a relative link). This is so that a link like `../parent` can be resolved to ../parent.html, ../parent.doc, ../parent.pdf, depending on the type of document being rendered.

**Comment by Intelligent2013** [comment]
common.xsl updated for `link@updatetype` processing.
