### ISSUE TITLE
(URGENT) Update Ribose PDF to new layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#99]
[Ribose Document Design_v2.pdf](https://github.com/metanorma/metanorma-ribose/files/6565828/Ribose.Document.Design_v2.pdf)

Described in https://github.com/metanorma/mn-native-pdf/issues/125

> Ribose Whitepaper (text in header)
> author's list
> RNP and Confium team, Ribose Inc.
> Delivered to nistir-8214A-comments@nist.gov

These data items are present in the XML, we need to make this customisable.

**Comment by Intelligent2013** [comment]
Used fonts:
- HelveticaNeue-Light
- HelveticaNeue-Light Italic
- HelveticaNeue-Medium
- HelveticaNeue-Bold

**Comment by ronaldtse** [comment]
@Intelligent2013 let’s use Source Sans for now, Helvetica Neue isn’t a free font.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 let’s use Source Sans for now, Helvetica Neue isn’t a free font.

@ronaldtse ok.

**Comment by Intelligent2013** [comment]
> These data items are present in the XML

@ronaldtse I've generated XML from https://github.com/metanorma/mn-samples-ribose/sources/nistir-8214a but still I don't see in xml these data:
- Ribose Group Inc.
- Author's list
- Unrestricted word
- RNP and Confium team, Ribose Inc.
- Ribose Group Inc
- Ribose Whitepaper (I think that we should just get 'Ribose' + 1st letter uppercased doctype, right?)

To generate XML I did:
```
git clone https://github.com/metanorma/mn-samples-ribose
cd mn-samples-ribose
bundle update
bundle exec metanorma -t ribose -x pdf sources/nistir-8214a/nistir-8214a-comments.adoc 
```
What I did wrong?

**Comment by ronaldtse** [comment]
@Intelligent2013 I have just added those missing attributes there. Can you re-check? I also have used the doctype "report" instead of "white paper" as it wasn't allowed in the flavor. Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse Ribose pdf xslt updated.
Resulted PDF: [nistir-8214a-comments.presentation.pdf](https://github.com/metanorma/metanorma-ribose/files/6569079/nistir-8214a-comments.presentation.pdf)

There are differences between data from design Layout and resulted PDF:
### 1.
design PDF:
![image](https://user-images.githubusercontent.com/5559926/120168152-3bdf9480-c207-11eb-92c2-56346b38900a.png)

resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/120168230-5154be80-c207-11eb-8526-bfd8c2336b93.png)

Reason: xslt gets value from `/rsd-standard/bibdata/ext/editorialgroup/committee` (RNP and Confium team)

### 2.
design PDF:
![image](https://user-images.githubusercontent.com/5559926/120168423-7f3a0300-c207-11eb-9852-0c07007613cc.png)

resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/120168457-895c0180-c207-11eb-9dec-7827fe091266.png)

Reason: in xml only 4 authors.

### 3.
design PDF:
![image](https://user-images.githubusercontent.com/5559926/120168512-9d9ffe80-c207-11eb-987d-c29e01c48b9f.png)

resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/120168537-a690d000-c207-11eb-9c0f-f8ccf4647df4.png)

Reason: in xml `<localized-string key="table_of_contents" language="en">Table of contents</localized-string>`

### 4.
design PDF:
![image](https://user-images.githubusercontent.com/5559926/120168652-ca541600-c207-11eb-9da1-2e73bd594847.png)

resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/120168796-f2dc1000-c207-11eb-8725-df185b40c3e9.png)

Reason: in xml there isn't standalone value `Ribose`, xslt gets value from `/rsd-standard/bibdata/contributor[role/@type='publisher']/organization/name`.

**Comment by ronaldtse** [comment]
> Reason: xslt gets value from /rsd-standard/bibdata/ext/editorialgroup/committee (RNP and Confium team)

This is okay.

> Reason: in xml only 4 authors.

This is good, fixed.

> Reason: in xml <localized-string key="table_of_contents" language="en">Table of contents</localized-string>

Need help from @opoudjis .

> Reason: in xml there isn't standalone value

I think we do "Ribose {doctype}" directly for indicating doctype. Regardless of the publisher the doctype remains the same. Thanks!
